#!/bin/bash
# zfs-snap-pac


# Command to get / dataset: zpool get bootfs -o value -pH

set -e

bootfs="none"
snapshotName="zfs-snap-pac-1-"

GetBootFS() {
    bootfs=$(zpool get bootfs -o value -pH | grep -v '-' | tail -n1)
}

GetSnapshotName() {
    local time=$(date +%s)
    snapshotName="$snapshotName$time"
}

CreateSnapshot() {
    echo "$bootfs@$snapshotName"
    if [ "$bootfs" == "none" ]
    then
        echo "Could not get BOOTFS/Root dataset! Stopping..."
        exit 1
    fi
    if [ "$snapshotName" == "zfs-snap-pac-1-" ]
    then
        echo "Could not generate a valid snapshot name! Stopping..."
        exit 1
    fi


    $(zfs snapshot $bootfs@$snapshotName)
    echo "Done!"
}

GetBootFS
GetSnapshotName
CreateSnapshot
