#!/bin/bash

# MIT License
#
# Copyright (c) 2022 Tomás Duarte
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# Command to get / dataset: zpool get bootfs -o value -pH

set -e

bootfs="none"
snapshotName="zfs-snap-pac-1-"

GetBootFS() {
    bootfs=$(zpool get bootfs -o value -pH)
}

GetSnapshotName() {
    local time=$(date +%s)
    snapshotName="$snapshotName$time"
}

CreateSnapshot() {
    echo "$bootfs@$snapshotName"
    if [ "$bootfs" == "none" ]
    then
        echo "Could not get BOOTFS/Root dataset! Stopping..."
        exit 1
    fi
    if [ "$snapshotName" == "zfs-snap-pac-1-" ]
    then
        echo "Could not generate a valid snapshot name! Stopping..."
        exit 1
    fi


    $(zfs snapshot $bootfs@$snapshotName)
    echo "Done!"
}

GetBootFS
GetSnapshotName
CreateSnapshot
